### ISSUE TITLE
FireStoreのフィールド名

### ISSUE THREAD

**Issue by Takapy1** [Ayato-kosaka/react-itinerary#104]
@Ayato-kosaka 
<representativeのスペルミス>
planGroupフィールド名にスペルミスがある

representivePlanID, representiveStartTime → representativePlanID, representativeStartTime

<IDの表記に関して>
itineraryIdは先頭だけ大文字
representativePlanIDは２文字とも大文字で統一できていない

これらって簡単に修正できる？

**Comment by Takapy1** [comment]
一応コードでは
representativeIdみたいにIdで統一する
（キャメルケースで書くことになっていたから）

**Comment by Ayato-kosaka** [comment]
@Takapy1 
全ファイル検索+全置換ができるからそんなに時間かからないはず！

IDに統一しようか。
Id ってあんまり見ないよね？笑

**Comment by Ayato-kosaka** [comment]
> 一応コードでは
representativeIdみたいにIdで統一する
（キャメルケースで書くことになっていたから）

あれ、Idが一般的？

**Comment by Takapy1** [comment]
@Ayato-kosaka 
IDの方がわかりやすいけど、itineraryIdとか引数で使っているから、大変かなと思ったけど、問題なさそうならIDの方がいいかな

**Comment by Ayato-kosaka** [comment]
了解した！

**Comment by Takapy1** [comment]
@Ayato-kosaka
IDで統一で！ 
てかFireStoreのフィールドをIDにするのはこさがやって、
プログラムの方の一括変更は俺がついでにやってもいいかな？

**Comment by Ayato-kosaka** [comment]
@Takapy1 
一括変換はお願いするわ！


Firestoreの方は、
フィールド登録とかせずに、apiで入れたものが何でも入る仕組みやから、
特に設定しなくても、フロントの連想配列の形を変えて送ったらそのまま登録されるよ！

**Comment by Takapy1** [comment]
@Ayato-kosaka 
すでにしおりデータ作成しているものに関してはデータ参照できなくなるんだけど、
これはどうしようか

**Comment by Ayato-kosaka** [comment]
@Takapy1 
うわーー
たしかにそうじゃん
リリースの直前に、今あるレコード全部置換するわ！
サブブランチ上では、開発進めれるで問題なさそう？
